version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
        - esdata:/usr/share/elasticsearch/data
        
  milvus:
    container_name: milvus
    image: milvusdb/milvus:1.1.1-cpu-d061621-330cc6
    ports:
      - 19530:19530 
      - 19121:19121
    volumes:
        - milvusdata:/var/lib/milvus
        
  weaviate:
    image: semitechnologies/weaviate:1.14.0
    ports:
      - 8081:8080
    environment:
        QUERY_DEFAULTS_LIMIT: 25
        AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
        PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
        DEFAULT_VECTORIZER_MODULE: 'none'
        ENABLE_MODULES: ''
        CLUSTER_HOSTNAME: 'node1'  
    volumes:
      - weaviatedata:/var/lib/weaviate
volumes:
  esdata:
  weaviatedata:
  milvusdata: