#name: workshop
channels:
  - conda-forge
dependencies:
  - python==3.7.*
  - pip
  - mamba
  - nb_conda_kernels
  - pyarrow==9.0.* 
  - lxml==4.9.*
  - pip:
      - google-cloud-bigquery-storage 
      - elasticsearch==8.4.*
      - weaviate-client==3.8.0
      - pandarallel==1.6.*
      - milvus==2.1.*
      - rich==12.6.*
      - jupyterlab-execute-time==2.1.*
      - sentence-transformers==2.2.*
      - ipywidgets==8.0.*
      - pyarrow==10.0.*
      - gcsfs==2022.10.*
      - papermill==2.3.*
      - rank_bm25==0.2.*
      - faiss_cpu==1.7.*
      - datasets==2.6.*
      - sentence-transformers==2.2.*
      - transformers==4.24.*


