# https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html#optimization
scheduling:
    userScheduler:
        enabled: true
    podPriority:
        enabled: true
    userPlaceholder:
        enabled: true
        # Specify five dummy user pods will be used as placeholders
        replicas: 1
    userPods:
        nodeAffinity:
            matchNodePurpose: require
cull:
    enabled: true
    timeout: 3600
    every: 300
singleuser:
    cpu:
        limit: 4
        guarantee: 4
    memory:
        limit: 8G
        guarantee: 8G
    image:
        # You should replace the "latest" tag with a fixed version from:
        # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
        # Inspect the Dockerfile at:
        # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
        name: gcr.io/np-public-training/semantic-search-workshop
        tag: v1.0
    #defaultUrl: /lab
    # extraEnv:
    #     GOOGLE_APPLICATION_CREDENTIALS: /etc/secrets/keyfile.json
    storage:
      type: none
        # extraVolumes:
        #     - name: gcsfs-creds
        #       secret:
        #         secretName: gcsfs-creds
        #         items:
        #             - key: keyfile.json
        #               path: keyfile.json
        # extraVolumeMounts:
        #     - name: gcsfs-creds
        #       mountPath: /etc/secrets
        #       readOnly: true
    lifecycleHooks:
        postStart:
            exec:
                command:
                    - sh
                    - -c
                    - "bash /tmp/workshop/workshop_infra/scripts/container_startup.sh"
    extraContainers:
        - name: elastic-search
          image: elasticsearch:8.7.0
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
        # - name: milvus
        #   image: gcr.io/np-public-training/custom-milvus:v2.1.4-1
        # - name: weaviate
        #   image: semitechnologies/weaviate:1.14.0
        #   env:
        #     - name: QUERY_DEFAULTS_LIMIT
        #       value: "25"
        #     - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
        #       value: "true"
        #     - name: PERSISTENCE_DATA_PATH
        #       value: /var/lib/weaviate
        #     - name: DEFAULT_VECTORIZER_MODULE
        #       value: none
        #     - name: ENABLE_MODULES
        #       value: ""
        #     - name: CLUSTER_HOSTNAME
        #       value: node1
# proxy:
#   https:
#     enabled: true
#     hosts:
#       - hub.np.training
#     letsencrypt:
#       contactEmail: npatta01@gmail.com
#   service:
#     loadBalancerIP: "34.145.156.81"
# proxy:
#   service:
#     loadBalancerIP: "34.145.156.81"

hub:
    config:
        Authenticator:
            admin_users:
                - npatta01
                - vishalkumar95
                - mzengin
                - rkyadav-ncsu

